# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Kaninik Baradi"
tagline:          "Complex Systems Engineering & Management • Climate Risk • Public policy"
description:      "Delivering complex projects. Driving systemic change."
url:              "https://mechakaradi.github.io"
baseurl:          "/"

author:
  name:           'Kaninik Baradi'
  email:           "kaninikbaradi@gmail.com"
  linkedin:        "https://www.linkedin.com/in/kaninik-baradi/"

paginate:         5
paginate_path:    "/page:num/"

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
